config/routes.rb
SampleApp::Application.routes.draw do

  resources :attendances

  resources :attendaces

  resources :rankings

  resources :events

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :questions
  
  root :to => "users#new"

  match '/about',   :to => 'pages#about'
  match '/leaders',   :to => 'users#leaders'

  match '/sms',   :to => 'answers#index'

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  belongs_to :user
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  # GET /rankings
  # GET /rankings.xml
  def index

    @rankings = Ranking.alla
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rankings }
    end

     @rankingslist = @current_user.rankings
     @sum = @rankinglist.sum(rankings)
     @count = @rankingslist.count
     @current_user.rank=@sum/@count






  end

  # GET /rankings/1
  # GET /rankings/1.xml
  def show
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ranking }
    end
  end

  # GET /rankings/new
  # GET /rankings/new.xml
  def new
    @ranking = Ranking.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ranking }
    end
  end

  # GET /rankings/1/edit
  def edit
    @ranking = Ranking.find(params[:id])
  end

  # POST /rankings
  # POST /rankings.xml
  def create
    @ranking = Ranking.new(params[:ranking])

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to(@ranking, :notice => 'Ranking was successfully created.') }
        format.xml  { render :xml => @ranking, :status => :created, :location => @ranking }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rankings/1
  # PUT /rankings/1.xml
  def update
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      if @ranking.update_attributes(params[:ranking])
        format.html { redirect_to(@ranking, :notice => 'Ranking was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.xml
  def destroy
    @ranking = Ranking.find(params[:id])
    @ranking.destroy

    respond_to do |format|
      format.html { redirect_to(rankings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assigner %><br />
    <%= f.text_field :assigner %>
  </div>
  <div class="field">
    <%= f.label :ranking %><br />
    <%= f.text_field :ranking %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <tr>
    <th>Assigner</th>
    <th>Ranking</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rankings.each do |ranking| %>
  <tr>
    <td><%= ranking.assigner %></td>
    <td><%= ranking.ranking %></td>
    <td><%= ranking.user %></td>
    <td><%= link_to 'Show', ranking %></td>
    <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
    <td><%= link_to 'Destroy', ranking, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assigner:</b>
  <%= @ranking.assigner %>
</p>

<p>
  <b>Ranking:</b>
  <%= @ranking.ranking %>
</p>

<p>
  <b>User:</b>
  <%= @ranking.user %>
</p>


<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>