config/routes.rb
SampleApp::Application.routes.draw do

  resources :attendances

  resources :attendaces

  resources :rankings

  resources :events

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :questions
  
  root :to => "users#new"

  match '/about',   :to => 'pages#about'
  match '/leaders',   :to => 'users#leaders'

  match '/sms',   :to => 'answers#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  attr_accessible :event_id

  belongs_to :user
  belongs_to :event
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  # GET /attendances
  # GET /attendances.xml
  def index
    @attendances = Attendance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attendances }
    end
  end

  # GET /attendances/1
  # GET /attendances/1.xml
  def show
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attendance }
    end
  end

  # GET /attendances/new
  # GET /attendances/new.xml
  def new
    @attendance = Attendance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attendance }
    end
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.xml
  def create
    @event = Event.find(params[:attendances][:event_id])
    current_user.join!(@event)
    respond_to do |format|
      format.html {redirect_to @event}
      format.js
    end
  end

  # PUT /attendances/1
  # PUT /attendances/1.xml
  def update
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      if @attendance.update_attributes(params[:attendance])
        format.html { redirect_to(@attendance, :notice => 'Attendance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attendance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.xml
  def destroy
    @event = Attendance.find(params[:id]).event
    current_user.leave!(@event)
    respond_to do |format|
      format.html {redirect_to @event}
      format.js
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.user %></td>
    <td><%= attendance.event %></td>
    <td><%= link_to 'Show', attendance %></td>
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', attendance, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attendance.user %>
</p>

<p>
  <b>Event:</b>
  <%= @attendance.event %>
</p>


<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>